server:
  port: 8080

spring:
  application:
    name: GateWay
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: apiRoute
              uri: http://api:8080
              predicates:
                - Path=/api/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: apiRouteCB
                    fallbackUri: forward:/fallback/api

resilience4j:
  timelimiter:
    instances:
      apiRouteCB:
        timeoutDuration: 3s


logging:
  level:
    root: info
